# Generated by Django 6.0.4 on 2026-04-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='tital',
            new_name='title',
        ),
    ]
